### ISSUE TITLE
More exception detail on DefineState and AddTransition

### ISSUE THREAD

**Issue by apazureck** [Ed-ward/Binstate#4]
Hi,

First of all, thanks for sharing your project. It looks really great.

I had trouble getting started, though. When I use an enum, like one in your example, an enum with value 0 (default) will throw an argument null exception on `Builder.DefineState` and `Config.State.AddTransition`. This is a little bit confusing. Could you provide some hint, that 0 on int or enum is also considered null?

Also I think your elevator example might also throw that exception, as the nullcheck is performed on Events, too. At least my enum did throw that exception.

Thanks and cheers!

**Comment by Ed-Pavlov** [comment]
This is done with intent, because there are "dynamic" transition implemented and "default" value means "no transition should be performed". See `AddTransition([NotNull] TEvent @event, [NotNull] Func<TState> getState) ` declaration. Moreover it's a bad practice to have a meaningfull default value in the enum. By coincidence [I've written about it last week](https://twitter.com/_pavloved/status/1319650863875502080).

But maybe it's not a buisness of a library to force good practices, you are right :)
Will try to make a specialization of dynamic transition for value types.

**Comment by Ed-Pavlov** [comment]
I've relaxed requirements for values which can be used as a state id. For now 'default' value of the value type can be used. New overload of AddTransition method is added to handle such values for dynamic transitions.

https://www.nuget.org/packages/Binstate/1.0.26

**Comment by apazureck** [comment]
Hi,

No, please do not relax that requirement. It is absolutely OK to force others to program. Just provide more information in the **Exception Message** to help out others to understand what they are doing wrong. In my case I just checked your source code here. I absolutely got, why you are doing this.

Like

```
The default value must not be used for adding a transition / event.
It indicates, that no transition should be performed later on. If you 
are using a not nullable type for your state or event, do not use 
the default value as transition.
```

Thanks and best regards!

PS: I could only think of one case where it could be trouble: When you are using an enum of another library for a state, which uses 0 for some state.

**Comment by Ed-Pavlov** [comment]
>  _I could only think of one case where it could be trouble: When you are using an enum of another library for a state, which uses 0 for some state._
I also have thought about it, that is why I decided to remove this constraint :)
